# -*- coding: utf-8 -*-
"""Binary Search

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qIg-S6Iyv340TZE1y22Jdq4ZHo12cdpN
"""

list= [1,2,13,4,15,6,11,9,19,10]
list.sort()
first=0
last=len(list)-1
mid= (first+last)//2
item=int(input("Enter the element to be searched: "))
found=False
while ( first<=last and not found):
  mid= (first+last)//2
  if(list[mid]==item):
    print(f"found at position {mid}")
    found=True
  else:
    if item<list[mid]:
      last = mid-1
    else:
      first=mid+1

if found==False:
  print("Number not found !")